### ISSUE TITLE
Empty meta `description` needs to be overwritten with `key` to avoid duplicate

### ISSUE THREAD

**Issue by eddybrando** [gridsome/gridsome#511]
## Description

When defining a **meta description** one must always overwrite the default **meta description** generated in `head.js`, even if `config.siteDescription` is empty.

Not explicitly setting `key: 'description'` results in an unnecessary duplicate of the **meta description** tag and the content not being taken into account for SEO, since the first empty **meta description** tag gets prioritised.

I believe we should check in `head.js` if `config.siteDescription` is set and only then create the **meta description**.

### Steps to reproduce

1. Don't set the `siteDescription` in `gridsome.config.js`.
2. Create a page and add `{ name: 'description', content: 'foo' }` to the `metaInfo.meta` array.
3. Check for **meta description** tags in the rendered page.

### Expected result

Only one **meta description** tag with `content="foo"` gets rendered, thus telling the SEO crawlers that the description of the page is "foo".

### Actual result

Two **meta description** tag get rendered. The first one with an empty `content` attribute. The second one with `content="foo"`.

The SEO crawlers may (and usually will) identify the content of the page as being empty.

### Environment

<pre><code>
Libs:
- gridsome version: 0.6.4
- @gridsome/cli version: 0.2.0

Browser:
- [X] Chrome (desktop) version 75.0.3770.90
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 11.2.0
- Platform:  Mac

Others:

</code></pre>

**Comment by tpalmer75** [comment]
Just filed https://github.com/gridsome/gridsome/issues/516. Slightly different, but could be related.
