### ISSUE TITLE
All "description" meta tags empty on rendered page

### ISSUE THREAD

**Issue by tpalmer75** [gridsome/gridsome#516]
## Description

The content attribute of description meta tags render as empty on my live site.

### Steps to reproduce

(Can be seen on my sandbox [here](https://uxtools-gridsome-2019.netlify.com/))

Add the following to your main.js file:

```
head.meta.push({
    key: 'description',
    name: 'description',
    content: `foo`
  })
head.meta.push({
    key: 'og:description',
    name: 'og:description',
    content: `foo`
  })
head.meta.push({
    key: 'twitter:description',
    name: 'twitter:description',
    content: `foo`
  })
```

### Expected result

In both dev and production environments, the tags should render as:
```
<meta data-key="description" name="description" content="foo" data-vue-tag="true">
etc.
```

### Actual result

Renders normally in dev, but in production renders as:
```
<meta data-vue-tag="true" data-key="description" name="description" content="">
etc.
```

### Environment

<pre><code>
Libs:
- gridsome version: 0.6.0
- @gridsome/cli version: Not sure

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by hjvedvik** [comment]
Looks like overriding meta tags by `key` only works when overriding form a child component, like pages or templates. I'll fix this by not adding the default `description` tag if `siteDescription` is empty.

**Comment by Al-Rozhkov** [comment]
We definitely should close this one. Fix for the issue has been commited (including test).
